### ISSUE TITLE
Getting this error after setting locale

### ISSUE THREAD

**Issue by 7dobi** [jaisharx/next-zero-intl#2]
<img width="1005" alt="Screen Shot 2022-01-09 at 01 01 09" src="https://user-images.githubusercontent.com/87612196/148656874-cacfd97b-ca3f-4d83-9d0a-3d22a94b72f5.png">

**Comment by jaisharx** [comment]
Hey @7dobi Sorry for such late response, but this library was not maintained for some time. But now I am in the process of a large refactor and soon everything should work. Thanks for your patience!

**Comment by 7dobi** [comment]
Hey @jaisharx, I can't install next-zero-intl package now, is it removed?

**Comment by jaisharx** [comment]
I'm currently working on a big refactor, things might be a bit rusty for few days.

**Comment by jaisharx** [comment]
Sorry there was an issue with the older versions, the latest version (v2.1.0) should fix everything. Feel free to re-open the issue if it still doesn't work for you.
